"""
Label Generator Module for XAUUSD Trading System.

Constructs prediction targets for ML model training and evaluation.
CRITICAL invariant: Labels shift backward in time (looking forward), so for row T,
label[T] reflects price action at T+horizon.
Features computed at or before row T MUST NOT use any columns generated by this module.
"""

import pandas as pd
import numpy as np


def add_direction_target(
    df: pd.DataFrame,
    horizon: int = 1,
    threshold: float = 0.30,
    price_col: str = "close",
    target_col: str = "target_direction",
) -> pd.DataFrame:
    """
    Computes 3-class directional target for given horizon:
      +1 : price[t+horizon] - price[t] > threshold  (UP)
      -1 : price[t+horizon] - price[t] < -threshold (DOWN)
       0 : |price[t+horizon] - price[t]| <= threshold (FLAT / WAIT)

    Args:
        df: Input DataFrame with OHLC data.
        horizon: Number of bars into the future (default: 1 bar).
        threshold: Absolute price change threshold in dollars (default: $0.30 for XAUUSD).
        price_col: Price column to evaluate (default: 'close').
        target_col: Name for generated target column.

    Returns:
        DataFrame with new target_col and target_return columns added.
    """
    out = df.copy()
    future_price = out[price_col].shift(-horizon)
    diff = future_price - out[price_col]

    # Compute continuous future return
    out["target_return"] = (future_price - out[price_col]) / out[price_col]

    # Compute 3-class discrete target
    target = pd.Series(0, index=out.index, dtype=int)
    target[diff > threshold] = 1
    target[diff < -threshold] = -1

    # Mark the last `horizon` rows as NaN because future price is unknown
    target.iloc[-horizon:] = np.nan
    out[target_col] = target
    out.loc[out.index[-horizon:], "target_return"] = np.nan
    return out


def add_binary_target(
    df: pd.DataFrame,
    horizon: int = 1,
    price_col: str = "close",
    target_col: str = "target_binary",
) -> pd.DataFrame:
    """
    Computes binary directional target:
      1 : price[t+horizon] > price[t]
      0 : price[t+horizon] <= price[t]

    Args:
        df: Input DataFrame.
        horizon: Number of bars into the future.
        price_col: Price column to evaluate.
        target_col: Name for generated target column.

    Returns:
        DataFrame with binary target column added.
    """
    out = df.copy()
    future_price = out[price_col].shift(-horizon)
    diff = future_price - out[price_col]

    target = pd.Series(0, index=out.index, dtype=float)
    target[diff > 0] = 1.0
    target.iloc[-horizon:] = np.nan

    out[target_col] = target
    return out
